### ISSUE TITLE
ColV simple summary object name is hard coded

### ISSUE THREAD

**Issue by CJREID** [maxlcummins/abricateR#2]
Dear Sir/Madam,

I hereby writeth to alerteth you to a bug that doth besmirch your code and good name.

On the 282nd line in this wonderful tome, thou hast hard-coded the numbers that doth appear in the assigned name of the ColV simple summary.

If thou could please debuggeth the code such that 'identity' and 'length' input variables appear instead, I should be greatly indebted to you.

Thank you milord.

Your humble liege,

Cameronius

**Comment by CJREID** [comment]
There are also some dcast deprecation related warnings whenever it runs that are supposedly going to become errors in the next version so might be a good time to address that if you've got the time.

**Comment by Tu6ka** [comment]
Dear cameronius, 
I desire to let thou wot that thy problem with the hardcoded name for the ColV simple summary hath been fixed and also the dcast depreciation warnings hast been doffed.

Your most humble and obedient servant,
Tu6ka
